version: "3"
# testing pipeline
services:
  leapcert-front:
    build:
      context: .
      dockerfile: Dockerfile
    image: leapcert-front:${IMAGE_TAG:-latest}
    container_name: leapcert-front
    ports:
      - "3030:3000"
    networks:
      - nginx_public

networks:
  nginx_public:
    external: true
