version: "3"
# testing pipeline
services:
  leapcert-front:
    image: leapcert-front:${IMAGE_TAG:-latest}
    deploy:
      restart_policy:
        condition: "any"
        delay: "0"
        max_attempts: 3
        window: "30s"
      resources:
        limits:
          cpus: "2.00"
          memory: "2G"
    ports:
      - "3030:3000"
    networks:
      - nginx_public

networks:
  nginx_public:
    external: true
