version: "3"
services:
  leapcert-front:
    build:
      context: .
      dockerfile: Dockerfile
    image: leapcert-front:${IMAGE_TAG:-latest}
    container_name: leapcert-front
    ports:
      - "3030:3000"
    restart: always
    networks:
      - leapcert-network

networks:
  leapcert-network:
